### DISCUSSION TITLE
Installation problem in PowerShell (Multiple Car support)

### DISCUSSION THREAD

**Discussion by bioniccid** [MartijnvanGeffen13/Volvo4evcc#41] [Q&A] [answered]
I'm trying to install Volvo4evcc ans I'm getting the following errrormessage - can someone help:

PS /home/pi> Import-Module "/home/pi/Volvo4Evcc/Volvo4Evcc.psd1"
Import-Module: The specified module '/home/pi/Volvo4Evcc/Volvo4Evcc.psd1' was not loaded because no valid module file was found in any module directory.

... I'm on an Raspberry with Debian (Bookworm) on it.

**Comment by MartijnvanGeffen13** [comment]
Is this path valid, 
mport-Module "/home/pi/Volvo4Evcc/Volvo4Evcc.psd1"

Note case sensitivity,   is this the path you installed the module in ?

**Reply by bioniccid** [reply]
... well - the folder ist there - see the picture (created by the "git clone" command). But when I try to enter it there comes an error messages (See also the picture)
<img width="710" alt="Bildschirmfoto 2025-02-19 um 15 35 47" src="https://github.com/user-attachments/assets/4e96aa8e-bd58-4756-9a97-0d557f1e0c6d" />

**Comment by MartijnvanGeffen13** [comment]
i would remove the folder and clone again looks like your clone did not process 

You should see something like this during cloning:
![image](https://github.com/user-attachments/assets/54fb2d4f-1661-47f0-8caf-cbfd995153f7)

**Reply by bioniccid** [reply]
mmmh, tried that already. But I will do it again... and post a picture.

**Reply by bioniccid** [reply]
well same same... on the picture you can see that I remove the folder, Clone it, start pwsh and get the same error message...
Well I have in line of that another question. I have 2 volvo's, so I need the multiple car version. But not quite sure what to do, when the wiki is saying "you can use the release on the branch: multiplecarsimpler V1.10.1". How do I install that one?
<img width="1017" alt="Bildschirmfoto 2025-02-19 um 15 50 12" src="https://github.com/user-attachments/assets/43c2459d-9667-4308-86a6-e601ac2e2cb4" />

**Reply by MartijnvanGeffen13** [reply]
if you have teams can you reach out to me on ************

**Comment by MartijnvanGeffen13** [comment, marked as answer]
Did the instructions in the wiki for multicar install help , did you managed to get it up and running

**Reply by bioniccid** [reply]
I did get it up and running... but on the raspberry it was kinda slow... so I tried it on my mac mini. And here it works great. What I didn't figure out was, how to set up the cronjob. right now it is just running in a terminal window...
<img width="1399" alt="Bildschirmfoto 2025-02-24 um 16 18 07" src="https://github.com/user-attachments/assets/1e3d05a1-8e89-4acf-89ee-afe5a5ace62c" />

**Reply by MartijnvanGeffen13** [reply]
Good to see you got it up and running, 

Not sure why the Pi whould be slow, I am running on a old surface pro 4 with 2x 400Mhz locked processor I7 mobile cpu (it only consumes 3 watt) and it only has 3% util on the proc.


If your SOC is slow detection when not charging / directly after plugged in , than you might want to check your loadpoint and set it to Allways pull soc even when not charging. Seen Volvo4evcc arranges optimal poll interval to the car you can have EVCC just poll every 1 or 5 or 10 whatever your happy with against the Volvo4evcc api.  
This is the SOC part of the below Yaml code example. Specially if you use solar optimized charging. you might want to set this 

```
loadpoints:
  - title: Alfen # display name for UI
    charger: Alfen # charger
    mode: "PV" # set default charge mode, use "off" to disable by default if charger is publicly available
    vehicle: EX30 # set default vehicle (disables vehicle detection)
    phases: 0 # electrical connection (normal charger: default 3 for 3 phase, 1p3p charger: 0 for "auto" or 1/3 for fixed phases)
    circuit: laadpaal
    enable:
      # switch on when there is at least 400 W surplus for 3 minute
      delay: 3m
      threshold: -400
    disable:
     # switch off if more than 1000 W are drawn from the mains for 7 minutes
      delay: 7m
      threshold: 1000
    soc:      #set Soc to allways pull against the Volvo4Evcc as this is a own hosted API and not the car directly hence we can pull faster when not charging
      poll:
        mode: connected
        interval: 5m
      estimate: true
```
